LandingPage configured
ebordenave/tech-dive-group-3 pull request #27
Opened 2023-03-06 15:53 UTC by helofel

2023-03-06 16:52 UTC, ebordenave approved these changes
this is great, thanks moses!

2023-03-06 16:56 UTC, ebordenave requested changes
you may need to do pull first

2023-03-06 19:39 UTC, helofel commented
why? I did a pull last night before I worked on it. I deleted a few files also. What's the issue.

2023-03-07 18:37 UTC, ebordenave approved these changes

2023-03-07 18:37 UTC, merged